# Generated by Django 4.2.6 on 2023-10-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name_plural': 'Gym'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainer'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'verbose_name_plural': 'WorkoutSession'},
        ),
    ]
