# Generated by Django 4.2.6 on 2023-10-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_options_alter_gym_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gym',
            table='api_gym',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='api_trainer',
        ),
        migrations.AlterModelTable(
            name='workoutsession',
            table='api_workoutsession',
        ),
    ]
