# Generated by Django 4.2.6 on 2023-10-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_client_options_alter_gym_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name_plural': 'Gym'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainer'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'verbose_name_plural': 'WorkoutSession'},
        ),
    ]
