# Generated by Django 4.2.6 on 2023-10-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_options_alter_gym_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gym',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trainer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workoutsession',
            table=None,
        ),
    ]
